namespace FunScript.HTML

open System
open FunScript.TypeScript

[<AutoOpen>]
module TypeScriptExtensions_1 =
    type Window with 
        [<FunScript.JSEmitInline("({0}[{1}])"); CompiledName("Item")>]
        member __.Item with get(i : string) : string = failwith "never" and set (i : string) (v : obj) : unit = failwith "never"

    type DOMStringMap with 
        [<FunScript.JSEmitInline("({0}[{1}])"); CompiledName("Item")>]
        member __.Item with get(i : string) : string = failwith "never" and set (i : string) (v : obj) : unit = failwith "never"

[<AutoOpen>]
[<ReflectedDefinition>]
module TypeScriptExtensions_2 =
    type HTMLEventStream<'T>(el: EventTarget, ev: string) =
        interface IObservable<'T> with
            member x.Subscribe observer =
                let listener = unbox (fun ev -> observer.OnNext(ev))
                el.addEventListener(ev, listener, false)
                new FunScript.Core.Events.ActionDisposable(fun () ->
                    el.removeEventListener(ev, listener, false)) :> IDisposable

    type AbstractWorker with 
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
    type ApplicationCache with 
            member __.ondownloadingStream with get() = HTMLEventStream<Event>(__, "downloading")
            member __.onprogressStream with get() = HTMLEventStream<ProgressEvent>(__, "progress")
            member __.onupdatereadyStream with get() = HTMLEventStream<Event>(__, "updateready")
            member __.oncachedStream with get() = HTMLEventStream<Event>(__, "cached")
            member __.onobsoleteStream with get() = HTMLEventStream<Event>(__, "obsolete")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
            member __.oncheckingStream with get() = HTMLEventStream<Event>(__, "checking")
            member __.onnoupdateStream with get() = HTMLEventStream<Event>(__, "noupdate")
    type AudioTrackList with 
            member __.onchangeStream with get() = HTMLEventStream<obj>(__, "change")
            member __.onaddtrackStream with get() = HTMLEventStream<TrackEvent>(__, "addtrack")
            member __.onremovetrackStream with get() = HTMLEventStream<PluginArray>(__, "removetrack")
    type CryptoOperation with 
            member __.oncompleteStream with get() = HTMLEventStream<obj>(__, "complete")
            member __.onerrorStream with get() = HTMLEventStream<obj>(__, "error")
            member __.onprogressStream with get() = HTMLEventStream<obj>(__, "progress")
            member __.onabortStream with get() = HTMLEventStream<obj>(__, "abort")
    type Document with 
            member __.onkeydownStream with get() = HTMLEventStream<KeyboardEvent>(__, "keydown")
            member __.onkeyupStream with get() = HTMLEventStream<KeyboardEvent>(__, "keyup")
            member __.onresetStream with get() = HTMLEventStream<Event>(__, "reset")
            member __.onhelpStream with get() = HTMLEventStream<Event>(__, "help")
            member __.ondragleaveStream with get() = HTMLEventStream<DragEvent>(__, "dragleave")
            member __.onfocusinStream with get() = HTMLEventStream<FocusEvent>(__, "focusin")
            member __.onseekedStream with get() = HTMLEventStream<Event>(__, "seeked")
            member __.ondurationchangeStream with get() = HTMLEventStream<Event>(__, "durationchange")
            member __.onblurStream with get() = HTMLEventStream<FocusEvent>(__, "blur")
            member __.onemptiedStream with get() = HTMLEventStream<Event>(__, "emptied")
            member __.onseekingStream with get() = HTMLEventStream<Event>(__, "seeking")
            member __.ondeactivateStream with get() = HTMLEventStream<UIEvent>(__, "deactivate")
            member __.oncanplayStream with get() = HTMLEventStream<Event>(__, "canplay")
            member __.ondatasetchangedStream with get() = HTMLEventStream<MSEventObj>(__, "datasetchanged")
            member __.onrowsdeleteStream with get() = HTMLEventStream<MSEventObj>(__, "rowsdelete")
            member __.onloadstartStream with get() = HTMLEventStream<Event>(__, "loadstart")
            member __.oncontrolselectStream with get() = HTMLEventStream<MSEventObj>(__, "controlselect")
            member __.ondragenterStream with get() = HTMLEventStream<DragEvent>(__, "dragenter")
            member __.onsubmitStream with get() = HTMLEventStream<Event>(__, "submit")
            member __.onchangeStream with get() = HTMLEventStream<Event>(__, "change")
            member __.onbeforeactivateStream with get() = HTMLEventStream<UIEvent>(__, "beforeactivate")
            member __.oncanplaythroughStream with get() = HTMLEventStream<Event>(__, "canplaythrough")
            member __.onbeforeupdateStream with get() = HTMLEventStream<MSEventObj>(__, "beforeupdate")
            member __.ondatasetcompleteStream with get() = HTMLEventStream<MSEventObj>(__, "datasetcomplete")
            member __.onsuspendStream with get() = HTMLEventStream<Event>(__, "suspend")
            member __.onerrorupdateStream with get() = HTMLEventStream<MSEventObj>(__, "errorupdate")
            member __.onmouseoutStream with get() = HTMLEventStream<MouseEvent>(__, "mouseout")
            member __.onmsthumbnailclickStream with get() = HTMLEventStream<MSSiteModeEvent>(__, "msthumbnailclick")
            member __.onmousewheelStream with get() = HTMLEventStream<MouseWheelEvent>(__, "mousewheel")
            member __.onvolumechangeStream with get() = HTMLEventStream<Event>(__, "volumechange")
            member __.oncellchangeStream with get() = HTMLEventStream<MSEventObj>(__, "cellchange")
            member __.onrowexitStream with get() = HTMLEventStream<MSEventObj>(__, "rowexit")
            member __.onrowsinsertedStream with get() = HTMLEventStream<MSEventObj>(__, "rowsinserted")
            member __.onpropertychangeStream with get() = HTMLEventStream<MSEventObj>(__, "propertychange")
            member __.ondragendStream with get() = HTMLEventStream<DragEvent>(__, "dragend")
            member __.ondragoverStream with get() = HTMLEventStream<DragEvent>(__, "dragover")
            member __.ondragstartStream with get() = HTMLEventStream<DragEvent>(__, "dragstart")
            member __.onmouseupStream with get() = HTMLEventStream<MouseEvent>(__, "mouseup")
            member __.ondragStream with get() = HTMLEventStream<DragEvent>(__, "drag")
            member __.onmouseoverStream with get() = HTMLEventStream<MouseEvent>(__, "mouseover")
            member __.onpauseStream with get() = HTMLEventStream<Event>(__, "pause")
            member __.onmousedownStream with get() = HTMLEventStream<MouseEvent>(__, "mousedown")
            member __.onclickStream with get() = HTMLEventStream<MouseEvent>(__, "click")
            member __.onwaitingStream with get() = HTMLEventStream<Event>(__, "waiting")
            member __.onstopStream with get() = HTMLEventStream<Event>(__, "stop")
            member __.onmssitemodejumplistitemremovedStream with get() = HTMLEventStream<MSSiteModeEvent>(__, "mssitemodejumplistitemremoved")
            member __.onstalledStream with get() = HTMLEventStream<Event>(__, "stalled")
            member __.onmousemoveStream with get() = HTMLEventStream<MouseEvent>(__, "mousemove")
            member __.onbeforeeditfocusStream with get() = HTMLEventStream<MSEventObj>(__, "beforeeditfocus")
            member __.onratechangeStream with get() = HTMLEventStream<Event>(__, "ratechange")
            member __.onprogressStream with get() = HTMLEventStream<obj>(__, "progress")
            member __.ondblclickStream with get() = HTMLEventStream<MouseEvent>(__, "dblclick")
            member __.oncontextmenuStream with get() = HTMLEventStream<MouseEvent>(__, "contextmenu")
            member __.onloadedmetadataStream with get() = HTMLEventStream<Event>(__, "loadedmetadata")
            member __.onerrorStream with get() = HTMLEventStream<Event>(__, "error")
            member __.onplayStream with get() = HTMLEventStream<Event>(__, "play")
            member __.onafterupdateStream with get() = HTMLEventStream<MSEventObj>(__, "afterupdate")
            member __.onplayingStream with get() = HTMLEventStream<Event>(__, "playing")
            member __.onabortStream with get() = HTMLEventStream<UIEvent>(__, "abort")
            member __.onfocusoutStream with get() = HTMLEventStream<FocusEvent>(__, "focusout")
            member __.onselectionchangeStream with get() = HTMLEventStream<Event>(__, "selectionchange")
            member __.onstoragecommitStream with get() = HTMLEventStream<StorageEvent>(__, "storagecommit")
            member __.ondataavailableStream with get() = HTMLEventStream<MSEventObj>(__, "dataavailable")
            member __.onreadystatechangeStream with get() = HTMLEventStream<Event>(__, "readystatechange")
            member __.onkeypressStream with get() = HTMLEventStream<KeyboardEvent>(__, "keypress")
            member __.onloadeddataStream with get() = HTMLEventStream<Event>(__, "loadeddata")
            member __.onbeforedeactivateStream with get() = HTMLEventStream<UIEvent>(__, "beforedeactivate")
            member __.onactivateStream with get() = HTMLEventStream<UIEvent>(__, "activate")
            member __.onselectstartStream with get() = HTMLEventStream<Event>(__, "selectstart")
            member __.onfocusStream with get() = HTMLEventStream<FocusEvent>(__, "focus")
            member __.ontimeupdateStream with get() = HTMLEventStream<Event>(__, "timeupdate")
            member __.onselectStream with get() = HTMLEventStream<UIEvent>(__, "select")
            member __.ondropStream with get() = HTMLEventStream<DragEvent>(__, "drop")
            member __.onendedStream with get() = HTMLEventStream<Event>(__, "ended")
            member __.onscrollStream with get() = HTMLEventStream<UIEvent>(__, "scroll")
            member __.onrowenterStream with get() = HTMLEventStream<MSEventObj>(__, "rowenter")
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
            member __.oninputStream with get() = HTMLEventStream<Event>(__, "input")
            member __.onmspointerdownStream with get() = HTMLEventStream<obj>(__, "mspointerdown")
            member __.onmsgesturedoubletapStream with get() = HTMLEventStream<obj>(__, "msgesturedoubletap")
            member __.onmsmanipulationstatechangedStream with get() = HTMLEventStream<obj>(__, "msmanipulationstatechanged")
            member __.onmspointerhoverStream with get() = HTMLEventStream<obj>(__, "mspointerhover")
            member __.onmscontentzoomStream with get() = HTMLEventStream<obj>(__, "mscontentzoom")
            member __.onmspointermoveStream with get() = HTMLEventStream<obj>(__, "mspointermove")
            member __.onmsgestureholdStream with get() = HTMLEventStream<obj>(__, "msgesturehold")
            member __.onmsgesturechangeStream with get() = HTMLEventStream<obj>(__, "msgesturechange")
            member __.onmsgesturestartStream with get() = HTMLEventStream<obj>(__, "msgesturestart")
            member __.onmspointercancelStream with get() = HTMLEventStream<obj>(__, "mspointercancel")
            member __.onmsgestureendStream with get() = HTMLEventStream<obj>(__, "msgestureend")
            member __.onmsgesturetapStream with get() = HTMLEventStream<obj>(__, "msgesturetap")
            member __.onmspointeroutStream with get() = HTMLEventStream<obj>(__, "mspointerout")
            member __.onmsinertiastartStream with get() = HTMLEventStream<obj>(__, "msinertiastart")
            member __.onmspointeroverStream with get() = HTMLEventStream<obj>(__, "mspointerover")
            member __.onmspointerupStream with get() = HTMLEventStream<obj>(__, "mspointerup")
            member __.onmsfullscreenerrorStream with get() = HTMLEventStream<obj>(__, "msfullscreenerror")
            member __.onmspointerenterStream with get() = HTMLEventStream<obj>(__, "mspointerenter")
            member __.onmsfullscreenchangeStream with get() = HTMLEventStream<obj>(__, "msfullscreenchange")
            member __.onmspointerleaveStream with get() = HTMLEventStream<obj>(__, "mspointerleave")
    type Element with 
            member __.onmspointerdownStream with get() = HTMLEventStream<obj>(__, "mspointerdown")
            member __.onmsgotpointercaptureStream with get() = HTMLEventStream<obj>(__, "msgotpointercapture")
            member __.onmsgesturedoubletapStream with get() = HTMLEventStream<obj>(__, "msgesturedoubletap")
            member __.onmspointerhoverStream with get() = HTMLEventStream<obj>(__, "mspointerhover")
            member __.onmsgestureholdStream with get() = HTMLEventStream<obj>(__, "msgesturehold")
            member __.onmspointermoveStream with get() = HTMLEventStream<obj>(__, "mspointermove")
            member __.onmsgesturechangeStream with get() = HTMLEventStream<obj>(__, "msgesturechange")
            member __.onmsgesturestartStream with get() = HTMLEventStream<obj>(__, "msgesturestart")
            member __.onmspointercancelStream with get() = HTMLEventStream<obj>(__, "mspointercancel")
            member __.onmsgestureendStream with get() = HTMLEventStream<obj>(__, "msgestureend")
            member __.onmsgesturetapStream with get() = HTMLEventStream<obj>(__, "msgesturetap")
            member __.onmspointeroutStream with get() = HTMLEventStream<obj>(__, "mspointerout")
            member __.onmsinertiastartStream with get() = HTMLEventStream<obj>(__, "msinertiastart")
            member __.onmslostpointercaptureStream with get() = HTMLEventStream<obj>(__, "mslostpointercapture")
            member __.onmspointeroverStream with get() = HTMLEventStream<obj>(__, "mspointerover")
            member __.onmspointerupStream with get() = HTMLEventStream<obj>(__, "mspointerup")
            member __.onmspointerenterStream with get() = HTMLEventStream<obj>(__, "mspointerenter")
            member __.onmspointerleaveStream with get() = HTMLEventStream<obj>(__, "mspointerleave")
    type HTMLBodyElement with 
            member __.ononlineStream with get() = HTMLEventStream<Event>(__, "online")
            member __.onblurStream with get() = HTMLEventStream<FocusEvent>(__, "blur")
            member __.onfocusStream with get() = HTMLEventStream<FocusEvent>(__, "focus")
            member __.onmessageStream with get() = HTMLEventStream<MessageEvent>(__, "message")
            member __.onerrorStream with get() = HTMLEventStream<Event>(__, "error")
            member __.onresizeStream with get() = HTMLEventStream<UIEvent>(__, "resize")
            member __.onafterprintStream with get() = HTMLEventStream<Event>(__, "afterprint")
            member __.onbeforeprintStream with get() = HTMLEventStream<Event>(__, "beforeprint")
            member __.onofflineStream with get() = HTMLEventStream<Event>(__, "offline")
            member __.onunloadStream with get() = HTMLEventStream<Event>(__, "unload")
            member __.onhashchangeStream with get() = HTMLEventStream<Event>(__, "hashchange")
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
            member __.onbeforeunloadStream with get() = HTMLEventStream<BeforeUnloadEvent>(__, "beforeunload")
            member __.onstorageStream with get() = HTMLEventStream<StorageEvent>(__, "storage")
            member __.onpopstateStream with get() = HTMLEventStream<PopStateEvent>(__, "popstate")
            member __.onpageshowStream with get() = HTMLEventStream<PageTransitionEvent>(__, "pageshow")
            member __.onpagehideStream with get() = HTMLEventStream<PageTransitionEvent>(__, "pagehide")
    type HTMLElement with 
            member __.onmouseleaveStream with get() = HTMLEventStream<MouseEvent>(__, "mouseleave")
            member __.onbeforecutStream with get() = HTMLEventStream<DragEvent>(__, "beforecut")
            member __.onkeydownStream with get() = HTMLEventStream<KeyboardEvent>(__, "keydown")
            member __.onmoveStream with get() = HTMLEventStream<MSEventObj>(__, "move")
            member __.onkeyupStream with get() = HTMLEventStream<KeyboardEvent>(__, "keyup")
            member __.onresetStream with get() = HTMLEventStream<Event>(__, "reset")
            member __.onhelpStream with get() = HTMLEventStream<Event>(__, "help")
            member __.ondragleaveStream with get() = HTMLEventStream<DragEvent>(__, "dragleave")
            member __.onfocusinStream with get() = HTMLEventStream<FocusEvent>(__, "focusin")
            member __.onseekedStream with get() = HTMLEventStream<Event>(__, "seeked")
            member __.ondurationchangeStream with get() = HTMLEventStream<Event>(__, "durationchange")
            member __.onblurStream with get() = HTMLEventStream<FocusEvent>(__, "blur")
            member __.onemptiedStream with get() = HTMLEventStream<Event>(__, "emptied")
            member __.onseekingStream with get() = HTMLEventStream<Event>(__, "seeking")
            member __.oncanplayStream with get() = HTMLEventStream<Event>(__, "canplay")
            member __.ondeactivateStream with get() = HTMLEventStream<UIEvent>(__, "deactivate")
            member __.ondatasetchangedStream with get() = HTMLEventStream<MSEventObj>(__, "datasetchanged")
            member __.onrowsdeleteStream with get() = HTMLEventStream<MSEventObj>(__, "rowsdelete")
            member __.onloadstartStream with get() = HTMLEventStream<Event>(__, "loadstart")
            member __.onlosecaptureStream with get() = HTMLEventStream<MSEventObj>(__, "losecapture")
            member __.ondragenterStream with get() = HTMLEventStream<DragEvent>(__, "dragenter")
            member __.oncontrolselectStream with get() = HTMLEventStream<MSEventObj>(__, "controlselect")
            member __.onsubmitStream with get() = HTMLEventStream<Event>(__, "submit")
            member __.onchangeStream with get() = HTMLEventStream<Event>(__, "change")
            member __.onlayoutcompleteStream with get() = HTMLEventStream<MSEventObj>(__, "layoutcomplete")
            member __.onbeforeactivateStream with get() = HTMLEventStream<UIEvent>(__, "beforeactivate")
            member __.oncanplaythroughStream with get() = HTMLEventStream<Event>(__, "canplaythrough")
            member __.onbeforeupdateStream with get() = HTMLEventStream<MSEventObj>(__, "beforeupdate")
            member __.onfilterchangeStream with get() = HTMLEventStream<MSEventObj>(__, "filterchange")
            member __.ondatasetcompleteStream with get() = HTMLEventStream<MSEventObj>(__, "datasetcomplete")
            member __.onsuspendStream with get() = HTMLEventStream<Event>(__, "suspend")
            member __.onmouseenterStream with get() = HTMLEventStream<MouseEvent>(__, "mouseenter")
            member __.onerrorupdateStream with get() = HTMLEventStream<MSEventObj>(__, "errorupdate")
            member __.onmouseoutStream with get() = HTMLEventStream<MouseEvent>(__, "mouseout")
            member __.onmousewheelStream with get() = HTMLEventStream<MouseWheelEvent>(__, "mousewheel")
            member __.onvolumechangeStream with get() = HTMLEventStream<Event>(__, "volumechange")
            member __.oncellchangeStream with get() = HTMLEventStream<MSEventObj>(__, "cellchange")
            member __.onrowexitStream with get() = HTMLEventStream<MSEventObj>(__, "rowexit")
            member __.onrowsinsertedStream with get() = HTMLEventStream<MSEventObj>(__, "rowsinserted")
            member __.onpropertychangeStream with get() = HTMLEventStream<MSEventObj>(__, "propertychange")
            member __.ondragendStream with get() = HTMLEventStream<DragEvent>(__, "dragend")
            member __.onbeforepasteStream with get() = HTMLEventStream<DragEvent>(__, "beforepaste")
            member __.ondragoverStream with get() = HTMLEventStream<DragEvent>(__, "dragover")
            member __.onmouseupStream with get() = HTMLEventStream<MouseEvent>(__, "mouseup")
            member __.ondragstartStream with get() = HTMLEventStream<DragEvent>(__, "dragstart")
            member __.onbeforecopyStream with get() = HTMLEventStream<DragEvent>(__, "beforecopy")
            member __.ondragStream with get() = HTMLEventStream<DragEvent>(__, "drag")
            member __.onmouseoverStream with get() = HTMLEventStream<MouseEvent>(__, "mouseover")
            member __.onpauseStream with get() = HTMLEventStream<Event>(__, "pause")
            member __.onmousedownStream with get() = HTMLEventStream<MouseEvent>(__, "mousedown")
            member __.onclickStream with get() = HTMLEventStream<MouseEvent>(__, "click")
            member __.onwaitingStream with get() = HTMLEventStream<Event>(__, "waiting")
            member __.onresizestartStream with get() = HTMLEventStream<MSEventObj>(__, "resizestart")
            member __.onpasteStream with get() = HTMLEventStream<DragEvent>(__, "paste")
            member __.onmoveendStream with get() = HTMLEventStream<MSEventObj>(__, "moveend")
            member __.onstalledStream with get() = HTMLEventStream<Event>(__, "stalled")
            member __.onmousemoveStream with get() = HTMLEventStream<MouseEvent>(__, "mousemove")
            member __.onbeforeeditfocusStream with get() = HTMLEventStream<MSEventObj>(__, "beforeeditfocus")
            member __.onratechangeStream with get() = HTMLEventStream<Event>(__, "ratechange")
            member __.onprogressStream with get() = HTMLEventStream<obj>(__, "progress")
            member __.ondblclickStream with get() = HTMLEventStream<MouseEvent>(__, "dblclick")
            member __.oncontextmenuStream with get() = HTMLEventStream<MouseEvent>(__, "contextmenu")
            member __.onloadedmetadataStream with get() = HTMLEventStream<Event>(__, "loadedmetadata")
            member __.onafterupdateStream with get() = HTMLEventStream<MSEventObj>(__, "afterupdate")
            member __.onerrorStream with get() = HTMLEventStream<Event>(__, "error")
            member __.onplayStream with get() = HTMLEventStream<Event>(__, "play")
            member __.onresizeendStream with get() = HTMLEventStream<MSEventObj>(__, "resizeend")
            member __.onplayingStream with get() = HTMLEventStream<Event>(__, "playing")
            member __.onfocusoutStream with get() = HTMLEventStream<FocusEvent>(__, "focusout")
            member __.onabortStream with get() = HTMLEventStream<UIEvent>(__, "abort")
            member __.ondataavailableStream with get() = HTMLEventStream<MSEventObj>(__, "dataavailable")
            member __.onreadystatechangeStream with get() = HTMLEventStream<Event>(__, "readystatechange")
            member __.onkeypressStream with get() = HTMLEventStream<KeyboardEvent>(__, "keypress")
            member __.onloadeddataStream with get() = HTMLEventStream<Event>(__, "loadeddata")
            member __.onbeforedeactivateStream with get() = HTMLEventStream<UIEvent>(__, "beforedeactivate")
            member __.onactivateStream with get() = HTMLEventStream<UIEvent>(__, "activate")
            member __.onmovestartStream with get() = HTMLEventStream<MSEventObj>(__, "movestart")
            member __.onselectstartStream with get() = HTMLEventStream<Event>(__, "selectstart")
            member __.onfocusStream with get() = HTMLEventStream<FocusEvent>(__, "focus")
            member __.ontimeupdateStream with get() = HTMLEventStream<Event>(__, "timeupdate")
            member __.onresizeStream with get() = HTMLEventStream<UIEvent>(__, "resize")
            member __.oncutStream with get() = HTMLEventStream<DragEvent>(__, "cut")
            member __.onselectStream with get() = HTMLEventStream<UIEvent>(__, "select")
            member __.ondropStream with get() = HTMLEventStream<DragEvent>(__, "drop")
            member __.oncopyStream with get() = HTMLEventStream<DragEvent>(__, "copy")
            member __.onendedStream with get() = HTMLEventStream<Event>(__, "ended")
            member __.onscrollStream with get() = HTMLEventStream<UIEvent>(__, "scroll")
            member __.onrowenterStream with get() = HTMLEventStream<MSEventObj>(__, "rowenter")
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
            member __.oninputStream with get() = HTMLEventStream<Event>(__, "input")
            member __.onmscontentzoomStream with get() = HTMLEventStream<obj>(__, "mscontentzoom")
            member __.oncuechangeStream with get() = HTMLEventStream<Event>(__, "cuechange")
            member __.onmsmanipulationstatechangedStream with get() = HTMLEventStream<obj>(__, "msmanipulationstatechanged")
    type HTMLFrameElement with 
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
    type HTMLFrameSetElement with 
            member __.ononlineStream with get() = HTMLEventStream<Event>(__, "online")
            member __.onblurStream with get() = HTMLEventStream<FocusEvent>(__, "blur")
            member __.onfocusStream with get() = HTMLEventStream<FocusEvent>(__, "focus")
            member __.onmessageStream with get() = HTMLEventStream<MessageEvent>(__, "message")
            member __.onerrorStream with get() = HTMLEventStream<Event>(__, "error")
            member __.onresizeStream with get() = HTMLEventStream<UIEvent>(__, "resize")
            member __.onafterprintStream with get() = HTMLEventStream<Event>(__, "afterprint")
            member __.onbeforeprintStream with get() = HTMLEventStream<Event>(__, "beforeprint")
            member __.onofflineStream with get() = HTMLEventStream<Event>(__, "offline")
            member __.onunloadStream with get() = HTMLEventStream<Event>(__, "unload")
            member __.onhashchangeStream with get() = HTMLEventStream<Event>(__, "hashchange")
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
            member __.onbeforeunloadStream with get() = HTMLEventStream<BeforeUnloadEvent>(__, "beforeunload")
            member __.onstorageStream with get() = HTMLEventStream<StorageEvent>(__, "storage")
            member __.onpageshowStream with get() = HTMLEventStream<PageTransitionEvent>(__, "pageshow")
            member __.onpagehideStream with get() = HTMLEventStream<PageTransitionEvent>(__, "pagehide")
    type HTMLIFrameElement with 
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
    type HTMLMarqueeElement with 
            member __.onbounceStream with get() = HTMLEventStream<Event>(__, "bounce")
            member __.onstartStream with get() = HTMLEventStream<Event>(__, "start")
            member __.onfinishStream with get() = HTMLEventStream<Event>(__, "finish")
    type HTMLMediaElement with 
            member __.onmsneedkeyStream with get() = HTMLEventStream<MSMediaKeyNeededEvent>(__, "msneedkey")
    type HTMLVideoElement with 
            member __.onMSVideoOptimalLayoutChanged with get() : System.Func<obj, obj> = failwith "never" and set (v : System.Func<obj, obj>) : unit = failwith "never"
            member __.onMSVideoFrameStepCompleted with get() : System.Func<obj, obj> = failwith "never" and set (v : System.Func<obj, obj>) : unit = failwith "never"
            member __.onMSVideoFormatChanged with get() : System.Func<obj, obj> = failwith "never" and set (v : System.Func<obj, obj>) : unit = failwith "never"
    type IDBDatabase with 
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
            member __.onabortStream with get() = HTMLEventStream<obj>(__, "abort")
    type IDBKeyRange with 
            member __.only(value : obj) : IDBKeyRange = failwith "never"
    type IDBOpenDBRequest with 
            member __.onupgradeneededStream with get() = HTMLEventStream<IDBVersionChangeEvent>(__, "upgradeneeded")
            member __.onblockedStream with get() = HTMLEventStream<Event>(__, "blocked")
    type IDBRequest with 
            member __.onsuccessStream with get() = HTMLEventStream<Event>(__, "success")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
    type IDBTransaction with 
            member __.oncompleteStream with get() = HTMLEventStream<Event>(__, "complete")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
            member __.onabortStream with get() = HTMLEventStream<obj>(__, "abort")
    type KeyOperation with 
            member __.oncompleteStream with get() = HTMLEventStream<obj>(__, "complete")
            member __.onerrorStream with get() = HTMLEventStream<obj>(__, "error")
    type MSBaseReader with 
            member __.onprogressStream with get() = HTMLEventStream<ProgressEvent>(__, "progress")
            member __.onabortStream with get() = HTMLEventStream<obj>(__, "abort")
            member __.onloadendStream with get() = HTMLEventStream<ProgressEvent>(__, "loadend")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
            member __.onloadStream with get() = HTMLEventStream<obj>(__, "load")
            member __.onloadstartStream with get() = HTMLEventStream<obj>(__, "loadstart")
    type MSInputMethodContext with 
            member __.oncandidatewindowshowStream with get() = HTMLEventStream<obj>(__, "candidatewindowshow")
            member __.oncandidatewindowhideStream with get() = HTMLEventStream<obj>(__, "candidatewindowhide")
            member __.oncandidatewindowupdateStream with get() = HTMLEventStream<obj>(__, "candidatewindowupdate")
    type MSWebViewAsyncOperation with 
            member __.oncompleteStream with get() = HTMLEventStream<obj>(__, "complete")
            member __.onerrorStream with get() = HTMLEventStream<obj>(__, "error")
    type MessagePort with 
            member __.onmessageStream with get() = HTMLEventStream<obj>(__, "message")
    type NavigatorOnLine with 
            member __.onLine with get() : bool = failwith "never" and set (v : bool) : unit = failwith "never"
    type ObjectURLOptions with 
            member __.oneTimeOnly with get() : bool = failwith "never" and set (v : bool) : unit = failwith "never"
    type SVGElement with 
            member __.onmouseoverStream with get() = HTMLEventStream<MouseEvent>(__, "mouseover")
            member __.onmousemoveStream with get() = HTMLEventStream<MouseEvent>(__, "mousemove")
            member __.onmouseoutStream with get() = HTMLEventStream<MouseEvent>(__, "mouseout")
            member __.ondblclickStream with get() = HTMLEventStream<MouseEvent>(__, "dblclick")
            member __.onfocusoutStream with get() = HTMLEventStream<FocusEvent>(__, "focusout")
            member __.onfocusinStream with get() = HTMLEventStream<FocusEvent>(__, "focusin")
            member __.onmousedownStream with get() = HTMLEventStream<MouseEvent>(__, "mousedown")
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
            member __.onmouseupStream with get() = HTMLEventStream<MouseEvent>(__, "mouseup")
            member __.onclickStream with get() = HTMLEventStream<MouseEvent>(__, "click")
    type SVGSVGElement with 
            member __.onzoomStream with get() = HTMLEventStream<obj>(__, "zoom")
            member __.onerrorStream with get() = HTMLEventStream<Event>(__, "error")
            member __.onresizeStream with get() = HTMLEventStream<UIEvent>(__, "resize")
            member __.onabortStream with get() = HTMLEventStream<UIEvent>(__, "abort")
            member __.onunloadStream with get() = HTMLEventStream<Event>(__, "unload")
            member __.onscrollStream with get() = HTMLEventStream<UIEvent>(__, "scroll")
    type TextTrack with 
            member __.oncuechangeStream with get() = HTMLEventStream<Event>(__, "cuechange")
            member __.onloadStream with get() = HTMLEventStream<obj>(__, "load")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
    type TextTrackCue with 
            member __.onenterStream with get() = HTMLEventStream<Event>(__, "enter")
            member __.onexitStream with get() = HTMLEventStream<Event>(__, "exit")
    type WebSocket with 
            member __.onopenStream with get() = HTMLEventStream<Event>(__, "open")
            member __.onmessageStream with get() = HTMLEventStream<obj>(__, "message")
            member __.oncloseStream with get() = HTMLEventStream<CloseEvent>(__, "close")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
    type Window with 
            member __.ondragendStream with get() = HTMLEventStream<DragEvent>(__, "dragend")
            member __.onkeydownStream with get() = HTMLEventStream<KeyboardEvent>(__, "keydown")
            member __.ondragoverStream with get() = HTMLEventStream<DragEvent>(__, "dragover")
            member __.onkeyupStream with get() = HTMLEventStream<KeyboardEvent>(__, "keyup")
            member __.onresetStream with get() = HTMLEventStream<Event>(__, "reset")
            member __.onmouseupStream with get() = HTMLEventStream<MouseEvent>(__, "mouseup")
            member __.ondragstartStream with get() = HTMLEventStream<DragEvent>(__, "dragstart")
            member __.ondragStream with get() = HTMLEventStream<DragEvent>(__, "drag")
            member __.onmouseoverStream with get() = HTMLEventStream<MouseEvent>(__, "mouseover")
            member __.ondragleaveStream with get() = HTMLEventStream<DragEvent>(__, "dragleave")
            member __.onafterprintStream with get() = HTMLEventStream<Event>(__, "afterprint")
            member __.onpauseStream with get() = HTMLEventStream<Event>(__, "pause")
            member __.onbeforeprintStream with get() = HTMLEventStream<Event>(__, "beforeprint")
            member __.onmousedownStream with get() = HTMLEventStream<MouseEvent>(__, "mousedown")
            member __.onseekedStream with get() = HTMLEventStream<Event>(__, "seeked")
            member __.onclickStream with get() = HTMLEventStream<MouseEvent>(__, "click")
            member __.onwaitingStream with get() = HTMLEventStream<Event>(__, "waiting")
            member __.ononlineStream with get() = HTMLEventStream<Event>(__, "online")
            member __.ondurationchangeStream with get() = HTMLEventStream<Event>(__, "durationchange")
            member __.onblurStream with get() = HTMLEventStream<FocusEvent>(__, "blur")
            member __.onemptiedStream with get() = HTMLEventStream<Event>(__, "emptied")
            member __.onseekingStream with get() = HTMLEventStream<Event>(__, "seeking")
            member __.oncanplayStream with get() = HTMLEventStream<Event>(__, "canplay")
            member __.onstalledStream with get() = HTMLEventStream<Event>(__, "stalled")
            member __.onmousemoveStream with get() = HTMLEventStream<MouseEvent>(__, "mousemove")
            member __.onofflineStream with get() = HTMLEventStream<Event>(__, "offline")
            member __.onbeforeunloadStream with get() = HTMLEventStream<BeforeUnloadEvent>(__, "beforeunload")
            member __.onratechangeStream with get() = HTMLEventStream<Event>(__, "ratechange")
            member __.onstorageStream with get() = HTMLEventStream<StorageEvent>(__, "storage")
            member __.onloadstartStream with get() = HTMLEventStream<Event>(__, "loadstart")
            member __.ondragenterStream with get() = HTMLEventStream<DragEvent>(__, "dragenter")
            member __.onsubmitStream with get() = HTMLEventStream<Event>(__, "submit")
            member __.onprogressStream with get() = HTMLEventStream<obj>(__, "progress")
            member __.ondblclickStream with get() = HTMLEventStream<MouseEvent>(__, "dblclick")
            member __.oncontextmenuStream with get() = HTMLEventStream<MouseEvent>(__, "contextmenu")
            member __.onchangeStream with get() = HTMLEventStream<Event>(__, "change")
            member __.onloadedmetadataStream with get() = HTMLEventStream<Event>(__, "loadedmetadata")
            member __.onplayStream with get() = HTMLEventStream<Event>(__, "play")
            member __.onerror with get() : ErrorEventHandlerDelegate = failwith "never" and set (v : FunScript.TypeScript.ErrorEventHandlerDelegate) : unit = failwith "never"
            member __.onplayingStream with get() = HTMLEventStream<Event>(__, "playing")
            member __.oncanplaythroughStream with get() = HTMLEventStream<Event>(__, "canplaythrough")
            member __.onabortStream with get() = HTMLEventStream<UIEvent>(__, "abort")
            member __.onreadystatechangeStream with get() = HTMLEventStream<Event>(__, "readystatechange")
            member __.onkeypressStream with get() = HTMLEventStream<KeyboardEvent>(__, "keypress")
            member __.onloadeddataStream with get() = HTMLEventStream<Event>(__, "loadeddata")
            member __.onsuspendStream with get() = HTMLEventStream<Event>(__, "suspend")
            member __.onfocusStream with get() = HTMLEventStream<FocusEvent>(__, "focus")
            member __.onmessageStream with get() = HTMLEventStream<MessageEvent>(__, "message")
            member __.ontimeupdateStream with get() = HTMLEventStream<Event>(__, "timeupdate")
            member __.onresizeStream with get() = HTMLEventStream<UIEvent>(__, "resize")
            member __.onselectStream with get() = HTMLEventStream<UIEvent>(__, "select")
            member __.ondropStream with get() = HTMLEventStream<DragEvent>(__, "drop")
            member __.onmouseoutStream with get() = HTMLEventStream<MouseEvent>(__, "mouseout")
            member __.onendedStream with get() = HTMLEventStream<Event>(__, "ended")
            member __.onhashchangeStream with get() = HTMLEventStream<Event>(__, "hashchange")
            member __.onunloadStream with get() = HTMLEventStream<Event>(__, "unload")
            member __.onscrollStream with get() = HTMLEventStream<UIEvent>(__, "scroll")
            member __.onmousewheelStream with get() = HTMLEventStream<MouseWheelEvent>(__, "mousewheel")
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
            member __.onvolumechangeStream with get() = HTMLEventStream<Event>(__, "volumechange")
            member __.oninputStream with get() = HTMLEventStream<Event>(__, "input")
            member __.onmspointerdownStream with get() = HTMLEventStream<obj>(__, "mspointerdown")
            member __.onmsgesturedoubletapStream with get() = HTMLEventStream<obj>(__, "msgesturedoubletap")
            member __.onmspointerhoverStream with get() = HTMLEventStream<obj>(__, "mspointerhover")
            member __.onmsgestureholdStream with get() = HTMLEventStream<obj>(__, "msgesturehold")
            member __.onmspointermoveStream with get() = HTMLEventStream<obj>(__, "mspointermove")
            member __.onmsgesturechangeStream with get() = HTMLEventStream<obj>(__, "msgesturechange")
            member __.onmsgesturestartStream with get() = HTMLEventStream<obj>(__, "msgesturestart")
            member __.onmspointercancelStream with get() = HTMLEventStream<obj>(__, "mspointercancel")
            member __.onmsgestureendStream with get() = HTMLEventStream<obj>(__, "msgestureend")
            member __.onmsgesturetapStream with get() = HTMLEventStream<obj>(__, "msgesturetap")
            member __.onmspointeroutStream with get() = HTMLEventStream<obj>(__, "mspointerout")
            member __.onmsinertiastartStream with get() = HTMLEventStream<obj>(__, "msinertiastart")
            member __.onmspointeroverStream with get() = HTMLEventStream<obj>(__, "mspointerover")
            member __.onpopstateStream with get() = HTMLEventStream<PopStateEvent>(__, "popstate")
            member __.onmspointerupStream with get() = HTMLEventStream<obj>(__, "mspointerup")
            member __.onpageshowStream with get() = HTMLEventStream<PageTransitionEvent>(__, "pageshow")
            member __.ondevicemotionStream with get() = HTMLEventStream<DeviceMotionEvent>(__, "devicemotion")
            member __.ondeviceorientationStream with get() = HTMLEventStream<DeviceOrientationEvent>(__, "deviceorientation")
            member __.onmspointerenterStream with get() = HTMLEventStream<obj>(__, "mspointerenter")
            member __.onpagehideStream with get() = HTMLEventStream<PageTransitionEvent>(__, "pagehide")
            member __.onmspointerleaveStream with get() = HTMLEventStream<obj>(__, "mspointerleave")
    type Worker with 
            member __.onmessageStream with get() = HTMLEventStream<obj>(__, "message")
    type XMLHttpRequest with 
            member __.ontimeoutStream with get() = HTMLEventStream<Event>(__, "timeout")
            member __.onreadystatechangeStream with get() = HTMLEventStream<Event>(__, "readystatechange")
            member __.onloadStream with get() = HTMLEventStream<Event>(__, "load")
            member __.onprogressStream with get() = HTMLEventStream<ProgressEvent>(__, "progress")
            member __.onabortStream with get() = HTMLEventStream<obj>(__, "abort")
            member __.onloadendStream with get() = HTMLEventStream<ProgressEvent>(__, "loadend")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
            member __.onloadstartStream with get() = HTMLEventStream<obj>(__, "loadstart")
    type XMLHttpRequestEventTarget with 
            member __.onprogressStream with get() = HTMLEventStream<ProgressEvent>(__, "progress")
            member __.onerrorStream with get() = HTMLEventStream<ErrorEvent>(__, "error")
            member __.onloadStream with get() = HTMLEventStream<obj>(__, "load")
            member __.ontimeoutStream with get() = HTMLEventStream<obj>(__, "timeout")
            member __.onabortStream with get() = HTMLEventStream<obj>(__, "abort")
            member __.onloadstartStream with get() = HTMLEventStream<obj>(__, "loadstart")
            member __.onloadendStream with get() = HTMLEventStream<ProgressEvent>(__, "loadend")
